# -*- coding: utf-8 -*-
"""Sensible Heat

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KH8tipRiefMW3T_0GpA3D15jjl3d-Hg2
"""

import pandas as pd
import numpy as np

#Define Constants
rho = 1.29
Cp = 1005
Ts = 0
Ch = 0.003

def sensibleheat(df):
  inMet = df

  Qh = np.empty(len(inMet.index))
  for i in range(len(inMet.index)):
    Qh[i] = (rho*Cp*(inMet.iloc[i][' windSpeed'])*((inMet.iloc[i]['T_C'])-Ts)*Ch)

  inMet['Qh'] = Qh.tolist()

  return inMet

print(sensibleheat(inMet))