# -*- coding: utf-8 -*-
"""QMelt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/187uZo6IWfyZ1KGJk5kzffbp-UTGYJaaZ
"""

import pandas as pd 
import numpy as np
import math

url = 'https://github.com/lilarickenbaugh/https-github.com-esproles-EB_Models/blob/758d9443d7aff14df6aa5a1db57387078188b135/matlabEB_lab/CENMET_INPUT_data.csv?raw=true'
inMet = pd.read_csv(url, index_col=0)

def melt(df): #Takes pandas dataframe as argument
  inMet = df #Rename dataframe

  #Set variables for constants 
  Rhow = 1000 
  L_f = 0.334e6
  B = 0.97

  Qmelt = np.empty(len(inMet.index)) #Create empty numpy array
  for i in range(len(inMet.index)):  #Calculate loss of latent heat of fusion through melt
      Qmelt[i] = ((inMet.iloc[i][' melt_m_hr']) * Rhow * L_f * B)

  inMet['Qmelt'] = Qmelt.tolist() #Add melt function to array
  
  return inMet #Return updated dataframe

print (melt(inMet))